# Generated by Django 4.0 on 2025-01-06 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chat_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chats_participated', to='app.appuser'),
        ),
    ]
