# Generated by Django 4.0 on 2025-01-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_chat_chat_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image_URL',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
