# Generated by Django 4.0 on 2025-01-13 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_message_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='video_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
