# Generated by Django 4.0 on 2025-01-14 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_appuser_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='video_url',
        ),
        migrations.AddField(
            model_name='message',
            name='video_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
