# Generated by Django 4.0 on 2025-01-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_appuser_video_url_message_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='video_url',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
