# Generated by Django 4.0 on 2025-01-15 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_message_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='audio_url',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
